
#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
env:
  global:
  - DOCKERHUB_PROJECT=dx-mgn-pool
before_install:
  - rm -rf node_modules
  - npm install -g ganache-cli@6.2.5
install:
  - npm install
before_script:
  - ganache-cli --defaultBalanceEther 500000000 --gasLimit=7e6 > /dev/null &
  - sleep 5
script:
  - cd $TRAVIS_BUILD_DIR/travscripts
  - "chmod +x ./BranchScript.sh && ./BranchScript.sh"
  - cd $TRAVIS_BUILD_DIR
deploy:
- provider: script
  script: bash travscripts/deploy_docker.sh staging
  on:
    branch: master
- provider: script
  script: bash travscripts/deploy_docker.sh develop
  on:
    branch: master